//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stella.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stella.Locale.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        public static string add_customer {
            get {
                return ResourceManager.GetString("add_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string add_service {
            get {
                return ResourceManager.GetString("add_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string birthdate {
            get {
                return ResourceManager.GetString("birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Service.
        /// </summary>
        public static string charge_service {
            get {
                return ResourceManager.GetString("charge_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer added successfully!.
        /// </summary>
        public static string customer_added {
            get {
                return ResourceManager.GetString("customer_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Details.
        /// </summary>
        public static string customer_details {
            get {
                return ResourceManager.GetString("customer_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer edited successfully!.
        /// </summary>
        public static string customer_edited {
            get {
                return ResourceManager.GetString("customer_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Info.
        /// </summary>
        public static string customer_info {
            get {
                return ResourceManager.GetString("customer_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer removed successfully!.
        /// </summary>
        public static string customer_removed {
            get {
                return ResourceManager.GetString("customer_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        public static string delete_record {
            get {
                return ResourceManager.GetString("delete_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string edit_customer {
            get {
                return ResourceManager.GetString("edit_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Notes.
        /// </summary>
        public static string edit_notes {
            get {
                return ResourceManager.GetString("edit_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string edit_service {
            get {
                return ResourceManager.GetString("edit_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when adding the customer..
        /// </summary>
        public static string error_adding_customer {
            get {
                return ResourceManager.GetString("error_adding_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when adding the service..
        /// </summary>
        public static string error_adding_service {
            get {
                return ResourceManager.GetString("error_adding_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when charging the service..
        /// </summary>
        public static string error_charging_service {
            get {
                return ResourceManager.GetString("error_charging_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when editing the customer..
        /// </summary>
        public static string error_editing_customer {
            get {
                return ResourceManager.GetString("error_editing_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when editing the record..
        /// </summary>
        public static string error_editing_record {
            get {
                return ResourceManager.GetString("error_editing_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when editing the service..
        /// </summary>
        public static string error_editing_service {
            get {
                return ResourceManager.GetString("error_editing_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading the customer info..
        /// </summary>
        public static string error_loading_customer_info {
            get {
                return ResourceManager.GetString("error_loading_customer_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading the services..
        /// </summary>
        public static string error_loading_services {
            get {
                return ResourceManager.GetString("error_loading_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when removing the customer..
        /// </summary>
        public static string error_removing_customer {
            get {
                return ResourceManager.GetString("error_removing_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when deleting the record..
        /// </summary>
        public static string error_removing_record {
            get {
                return ResourceManager.GetString("error_removing_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when removing the service..
        /// </summary>
        public static string error_removing_service {
            get {
                return ResourceManager.GetString("error_removing_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when retrieving the statistics..
        /// </summary>
        public static string error_stats {
            get {
                return ResourceManager.GetString("error_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert your Stella token.
        /// </summary>
        public static string insert_token {
            get {
                return ResourceManager.GetString("insert_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Services.
        /// </summary>
        public static string load_services {
            get {
                return ResourceManager.GetString("load_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stella Reader connected!.
        /// </summary>
        public static string reader_found {
            get {
                return ResourceManager.GetString("reader_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stella Reader not found. You may try again on the Settings page..
        /// </summary>
        public static string reader_not_found {
            get {
                return ResourceManager.GetString("reader_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: .
        /// </summary>
        public static string reader_status {
            get {
                return ResourceManager.GetString("reader_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string reconnect {
            get {
                return ResourceManager.GetString("reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record edited successfully!.
        /// </summary>
        public static string record_edited {
            get {
                return ResourceManager.GetString("record_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully!.
        /// </summary>
        public static string record_removed {
            get {
                return ResourceManager.GetString("record_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Customer.
        /// </summary>
        public static string remove_customer {
            get {
                return ResourceManager.GetString("remove_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service.
        /// </summary>
        public static string remove_service {
            get {
                return ResourceManager.GetString("remove_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customer.
        /// </summary>
        public static string search_customer {
            get {
                return ResourceManager.GetString("search_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Service.
        /// </summary>
        public static string search_service {
            get {
                return ResourceManager.GetString("search_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        public static string select_customer {
            get {
                return ResourceManager.GetString("select_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service added successfully!.
        /// </summary>
        public static string service_added {
            get {
                return ResourceManager.GetString("service_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service charged successfully!.
        /// </summary>
        public static string service_charged {
            get {
                return ResourceManager.GetString("service_charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service edited successfully!.
        /// </summary>
        public static string service_edited {
            get {
                return ResourceManager.GetString("service_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service removed successfully!.
        /// </summary>
        public static string service_removed {
            get {
                return ResourceManager.GetString("service_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Available.
        /// </summary>
        public static string services_available {
            get {
                return ResourceManager.GetString("services_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services loaded successfully!.
        /// </summary>
        public static string services_loaded {
            get {
                return ResourceManager.GetString("services_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Charge.
        /// </summary>
        public static string single_charge {
            get {
                return ResourceManager.GetString("single_charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stella Reader.
        /// </summary>
        public static string stella_reader {
            get {
                return ResourceManager.GetString("stella_reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string token {
            get {
                return ResourceManager.GetString("token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when validating the token..
        /// </summary>
        public static string token_error {
            get {
                return ResourceManager.GetString("token_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string transactions {
            get {
                return ResourceManager.GetString("transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome..
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
